plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'solutions.trp'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

dependencies {
    api 'com.fasterxml.jackson.core:jackson-databind:2.19.2'
    implementation 'org.apache.xmlgraphics:batik-transcoder:1.19'
    implementation 'org.apache.xmlgraphics:batik-codec:1.19'

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
