name: Build (Cross-platform, CMake)

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:

jobs:

  # macOS
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S Emulator -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package macOS app
        run: |
          mkdir package
          cp -R build/e_paper_emulator.app package/

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: package


  # Windows
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S Emulator -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package Windows exe
        run: |
          mkdir package
          copy build\Release\e_paper_emulator.exe package\

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: package


  # Linux
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S Emulator -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Package Linux binary
        run: |
          mkdir package
          cp build/e_paper_emulator package/
          chmod +x package/e_paper_emulator

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: package


  release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Zip artifacts
        run: |
          zip -r macos.zip macos-build
          zip -r windows.zip windows-build
          zip -r linux.zip linux-build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            macos.zip
            windows.zip
            linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}